version: '3.5'

services:

  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ CMD-SHELL, pg_isready -U admin ]
      interval: 5s
      timeout: 10s
      retries: 5
